version: '3.7'

services:
  jupyter:
    build: .
    init: true
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/jupyter
    command: jupyter-lab --ip=0.0.0.0 --allow-root --no-browser
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}

